# Generated by Django 2.2 on 2019-09-28 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('detailDesc', models.CharField(max_length=300)),
                ('answerCount', models.IntegerField(max_length=10)),
                ('lastModifiled', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ansContent', models.CharField(max_length=300)),
                ('ansDate', models.DateField(auto_now=True)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Questions')),
            ],
        ),
    ]
