# Generated by Django 2.2 on 2019-09-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='ansDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='lastModifiled',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
