# Generated by Django 2.2 on 2019-09-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='姓名'),
        ),
    ]
